//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34011
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tetris {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TetrisResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TetrisResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tetris.TetrisResource", typeof(TetrisResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap back {
            get {
                object obj = ResourceManager.GetObject("back", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap BackPic {
            get {
                object obj = ResourceManager.GetObject("BackPic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap block {
            get {
                object obj = ResourceManager.GetObject("block", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap BlockNull {
            get {
                object obj = ResourceManager.GetObject("BlockNull", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap BlockNull2 {
            get {
                object obj = ResourceManager.GetObject("BlockNull2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap blockOpacity {
            get {
                object obj = ResourceManager.GetObject("blockOpacity", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 俄罗斯方块 的本地化字符串。
        /// </summary>
        internal static string Caption {
            get {
                return ResourceManager.GetString("Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 继续 的本地化字符串。
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 System.IO.MemoryStream 的 System.IO.UnmanagedMemoryStream 类型的本地化资源。
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream DeleteLinesSound {
            get {
                return ResourceManager.GetStream("DeleteLinesSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   游戏结束
        ///按F2重新开始 的本地化字符串。
        /// </summary>
        internal static string GameOver {
            get {
                return ResourceManager.GetString("GameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重新开始：F2
        ///暂    停：F3
        ///退    出：ESC
        ///帮    助：F1
        ///凡人出品
        ///QQ:383449048
        ///技术交流群:338719786
        ///E-Mail:jksharp@163.com 的本地化字符串。
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 天空之城 的本地化字符串。
        /// </summary>
        internal static string Level1Name {
            get {
                return ResourceManager.GetString("Level1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 月牙之夜 的本地化字符串。
        /// </summary>
        internal static string Level2Name {
            get {
                return ResourceManager.GetString("Level2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢沁 的本地化字符串。
        /// </summary>
        internal static string Level3Name {
            get {
                return ResourceManager.GetString("Level3Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 踏古 的本地化字符串。
        /// </summary>
        internal static string Level4Name {
            get {
                return ResourceManager.GetString("Level4Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 诸神之诗 的本地化字符串。
        /// </summary>
        internal static string Level5Name {
            get {
                return ResourceManager.GetString("Level5Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 夜莺 的本地化字符串。
        /// </summary>
        internal static string Level6Name {
            get {
                return ResourceManager.GetString("Level6Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 王都炎上 的本地化字符串。
        /// </summary>
        internal static string Level7Name {
            get {
                return ResourceManager.GetString("Level7Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开文件失败 的本地化字符串。
        /// </summary>
        internal static string OpenFileError {
            get {
                return ResourceManager.GetString("OpenFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游戏暂停
        ///按F3继续 的本地化字符串。
        /// </summary>
        internal static string PauseDescript {
            get {
                return ResourceManager.GetString("PauseDescript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂停 的本地化字符串。
        /// </summary>
        internal static string PauseMenu {
            get {
                return ResourceManager.GetString("PauseMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不允许输入与其他操作相同的控制键！ 的本地化字符串。
        /// </summary>
        internal static string SameKey {
            get {
                return ResourceManager.GetString("SameKey", resourceCulture);
            }
        }
    }
}
